perl re_graph.pl -o t_01.png 'test'
perl re_graph.pl -o t_02.png '^Test'
perl re_graph.pl -o t_03.png '^ *#'
perl re_graph.pl -o t_04.png '^[ \t]*#'
perl re_graph.pl -o t_05.png '^\s*#'
perl re_graph.pl -o t_06.png '([^#]*)(#.*)'
perl re_graph.pl -o t_07.png 'a|b'
perl re_graph.pl -o t_08.png '^(([^#"]*|".*")*)(#.*)'
perl re_graph.pl -o t_09.png '^((?:[^#"]*|".*?")*)(#.*)'
perl re_graph.pl -o t_10.png '^((?:[^#"]*|".*?(?<!\\)")*)(#.*)'
